#!/bin/bash

# SYMFONY
alias g='git'
alias sf='bin/console'
alias sfcc='sf cache:clear'
alias sinit='sudo setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX app/cache app/logs ; sudo setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs ; sfcc'
alias rode='sf debug:router'
alias contde='sf debug:container'

# TEAMOCIL
alias symfony="teamocil --here symfony"

# TMUX
alias tmux='tmux -2'

# GIT
alias gpurge='purge = branch --merged master | grep -v master | xargs git branch -d'
alias gdiff="git diff"
alias gst="git st"

# DOCKER
alias dps='docker ps'
alias dim='docker images'
alias de='docker exec'
alias dcu='docker-compose up'
alias dce='docker-compose exec'
alias dc='docker-compose'
alias dcs='docker-compose stop'

# STUFF
alias myip='curl http://ipecho.net/plain ; echo'
alias bdl='./bin/behat -dl --lang=en'
